// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLkOA8JCCSOPqNBPHtU0nmqoFVUwsV2a0',
    appId: '1:20738478771:web:63a1134931ba57522016c6',
    messagingSenderId: '20738478771',
    projectId: 'sol-partner-f05c8',
    authDomain: 'sol-partner-f05c8.firebaseapp.com',
    storageBucket: 'sol-partner-f05c8.appspot.com',
    measurementId: 'G-YMZMRH68TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRfhpdpadFkMUm46uG_pmOs0r6Sa5a8Ug',
    appId: '1:20738478771:android:2bb7525d6c134a3b2016c6',
    messagingSenderId: '20738478771',
    projectId: 'sol-partner-f05c8',
    storageBucket: 'sol-partner-f05c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQYQKWBj1cmLYZIAOLY1py0k2MmuoCYyo',
    appId: '1:20738478771:ios:d2a8d4dbbb1df8b62016c6',
    messagingSenderId: '20738478771',
    projectId: 'sol-partner-f05c8',
    storageBucket: 'sol-partner-f05c8.appspot.com',
    iosBundleId: 'com.example.mishop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQYQKWBj1cmLYZIAOLY1py0k2MmuoCYyo',
    appId: '1:20738478771:ios:a9519760df70d92e2016c6',
    messagingSenderId: '20738478771',
    projectId: 'sol-partner-f05c8',
    storageBucket: 'sol-partner-f05c8.appspot.com',
    iosBundleId: 'com.example.mishop.RunnerTests',
  );
}
